### ISSUE TITLE
Bad error message if wide character in the stack.

### ISSUE THREAD

**Issue by tokuhirom** [rjbs/Email-Sender#17]
```
use strict;
use warnings;
use utf8;
use Email::Sender::Simple qw(sendmail);
use Email::MIME;

send_foo("\x{304a}");

sub send_foo {
    my $foo = shift;

    my $mail = Email::MIME->create();
    sendmail($mail);
}
```

This code should say "no recipients".
But it only says "Wide character in die". Because there is wide characters in the caller's arguments.

This behavior makes hard to debug.

(Moo enables `use warnings FATAL => 'all';` by strictures.pm)

**Comment by rjbs** [comment]
This is fixed by Moo v2, which will be required by the next release of Email-Sender.
