### ISSUE TITLE
Missing documentation: authentication

### ISSUE THREAD

**Issue by dankasak** [rjbs/Email-Sender#29]
I've checked:
 http://search.cpan.org/~rjbs/Email-Sender-1.300016/lib/Email/Sender.pm
 http://search.cpan.org/~rjbs/Email-Sender-1.300016/lib/Email/Sender/Simple.pm
 http://search.cpan.org/~rjbs/Email-Sender-1.300016/lib/Email/Sender/Manual.pm
 http://search.cpan.org/~rjbs/Email-Sender-1.300016/lib/Email/Sender/Manual/QuickStart.pm
 http://search.cpan.org/~rjbs/Email-Sender-1.300016/lib/Email/Sender/Transport.pm
 ... and found no references to authentication at all. I've seen old blog posts mentioning authentication, but none actually detailing it. Could I please be pointed to the documentation? Sorry if I've missed something obvious.

**Comment by rjbs** [comment]
Once you need auth, you need to set up your transport explicitly.  Presumably that means using https://metacpan.org/pod/Email::Sender::Transport::SMTP — and you should see the auth options detailed there.  Does that help?  Where do you suggest we put a pointer to this, where you might have found it better?
