### ISSUE TITLE
Email::Sender::Simple: Useless use of a constant ("220 OK") in void context

### ISSUE THREAD

**Issue by carnil** [rjbs/Email-Sender#30]
Hi

While preparing an update on Debian's side for Email::Sender I noticed the following:

```
perl -wc /usr/share/perl5/Email/Sender/Simple.pm
Useless use of a constant ("220 OK") in void context at /usr/share/perl5/Email/Sender/Simple.pm line 168.
```

is that on purpose? i was not sure to report that, since it is since mostly "forewer" that way but decided to ask via issue tracker.

Regards

**Comment by rjbs** [comment]
It's a little joke.  The warning only occurs when the Simple.pm file is the main compilation unit... which is basically never.
