### ISSUE TITLE
Can't locate object method "new" via package "Email::Sender::Transport::SMTP" at __FILE__

### ISSUE THREAD

**Issue by Kelicula** [rjbs/Email-Sender#31]
Per the instructions on CPAN I attempted to create a custom transport, this is what I got, from looking under the hood, I must assume the constructor is inherited?? 

Don't like to mess around too much in other peoples code. 
Any ideas?

**Comment by rjbs** [comment]
It sounds like you didn't load the plugin properly.  Could you show me the code you wrote, more or less?
