### ISSUE TITLE
"Wide character in subroutine entry"

### ISSUE THREAD

**Issue by SteveTheTechie** [rjbs/Email-Sender#32]
I received a report of the following error from one of my Japanese users, that appears to originate in line 218 of SMTP.pm.  Not sure how to resolve this.  (To address below removed by user to prevent spam bots from getting it.):

To: my address
 From: Mail Delivery Subsystem <MAILER-DAEMON@toastmastersclubs.org>
 Date: Sun, 19 Jul 2015 13:55:28 GMT
 Subject: Returned mail: see transcript for details

 The original message was received at Sun, 19 Jul 2015 13:55:22 GMT
 from rcpt-expgw.biglobe.ne.jp [133.208.98.3]

The following addresses had permanent fatal errors 
|/etc/tcmail.pl
 (reason: 255)
 (expanded from: <officers-683085@toastmastersclubs.org>)

Transcript of session follows 
Status: 500
 Content-type: text/html

 <h1>Software error:</h1>
 <pre>Can't locate object method "message" via package "Wide character in subroutine entry at /usr/local/share/perl5/Email/Sender/Transport/SMTP.pm line 218.
 " (perhaps you forgot to load "Wide character in subroutine entry at /usr/local/share/perl5/Email/Sender/Transport/SMTP.pm line 218.
 "?) at /etc/smrsh/tcmail.pl line 739.
 </pre>
 <p>
 For help, please send mail to this site's webmaster, giving this error message
 and the time and date of the error.

 </p>
 [Sun Jul 19 13:55:28 2015] tcmail.pl: Can't locate object method "message" via package "Wide character in subroutine entry at /usr/local/share/perl5/Email/Sender/Transport/SMTP.pm line 218.
 [Sun Jul 19 13:55:28 2015] tcmail.pl: " (perhaps you forgot to load "Wide character in subroutine entry at /usr/local/share/perl5/Email/Sender/Transport/SMTP.pm line 218.
 [Sun Jul 19 13:55:28 2015] tcmail.pl: "?) at /etc/smrsh/tcmail.pl line 739.
 554 5.3.0 unknown mailer error 255

**Comment by rjbs** [comment]
This line:

```
Can't locate object method "message" via package "Wide character in subroutine entry at 
/usr/local/share/perl5/Email/Sender/Transport/SMTP.pm line 218.
```

…indicates that probably what happened is that something caught an exception and tried calling `->message` on it without first checking that it was an Email::Sender::Failure.

The error itself is the result of the email message being improperly encoded.  I don't know how you generated it, but presumably the stringified form of the object past to `send_email` has characters in it beyond 0xFF, and those can't be transmitted across the wire.  The email message generation/encoding has to be fixed.

**Comment by SteveTheTechie** [comment]
Well, I do not generate the message, per se.   It comes to the apache server from the user's webmail/email client which passes it to my email handler code.   My email handler code reads it from stdin, and feeds it to Email::MIME.  Other than changing out some of the headers (to expand distribution lists) and inserting unsubscribe links for non-member emails, I am not altering the text.  

Since this email is fed to Email::MIME, I am presuming I could use one of the Email::MIME methods to force everything it gets to be a consistent encoding.  However, I am a bit at a loss as to which Email::MIME method to use to do that. (or how)

**Comment by SteveTheTechie** [comment]
Closing this issue...   It turns out the problem was some confusion that "message" was not a object method but rather a hash key.   The documentation on the error handling techniques for email sender is a bit vague... took me a long time and scanning your Perl module to figure this out.

**Comment by rjbs** [comment]
I'm not sure what you're suggesting happened.  I originally diagnosed it as something like this:

    my $ok = eval { ... ; 1 };
    unless ($ok) {
        my $error = $@;
        print $error->message;
    }

…and the error was not a Email::Sender::Failure, but a non-object error from Encode.  I don't understand what you're saying when you say that "message" was not an object method.  The error (`Can't locate object method "message"`) is generated by perl when `$x->message` can't find the method `message`.  So, hash keys don't seem involved.

Can you help me understand what happened?

**Comment by ernstki** [comment]
I understand this is a Perl error, and it's cropping up due to my persistent confusion with all the various environment variables, pragmata, and option bundles required [to get Perl to handle UTF-8](https://stackoverflow.com/questions/6162484/why-does-modern-perl-avoid-utf-8-by-default/6163129).

However, since this issue shows up at the top of search results for this specific error message, I hope this added context might help another user. So pay it no mind, @rjbs!

Here's the code I was using:

```perl
my $result = $e->transport(
    'SMTP', {
        host => 'localhost', port => '1025',
        sasl_username => $ME,
        sasl_password => $pass,
        debug => $ENV{DEBUG_SMTP}
    })->send;
```

and the error received in `send`ing was

```plain
Wide character in subroutine entry at /usr/share/perl/5.30/Net/SMTP.pm line 230.
```

The _reason_ for this error in my situation was that `$pass` contained a Unicode character (a right curly quote). If it were a production application, I'd be more interested in _actually_ dealing with the error, but in this case, it was actually easier for me to just change `$pass`.
