### ISSUE TITLE
Email Sender and retries

### ISSUE THREAD

**Issue by SteveTheTechie** [rjbs/Email-Sender#33]
The server that handles our system email is the same server used for generating Toastmasters club websites for each of the over 10,000 clubs that use the FreeToastHost system.  I do not have any control over that circumstance, and occasionally there are email delivery delays when the server is under heavy load.  (Mondays are typically slower.)  We average around 300,000 emails through the system in a given week.

When I was previously using Email::Send, I found that I could improve email delivery by implementing a retry loop with increasing sleep times between each retry up to a maximum number of retries.  (The loop was only used for certain types of delivery failures.)  Sometimes it would take longer for people to get their emails, but at least it would get delivered.

Now that I am using Email::Sender, I am wondering if I should get keep the retry loop given that the server setup is the same, or **if there is a built-in retry mechanism in Email::Sender**.  *I bring this up since I recently had a user mention that they had received two duplicates of the same email.*  I might expect that if there is a built-in retry mechanism in Email::Sender and the system was under heavy load.  I have asked the for more information from the user, but have not yet received it.

**Comment by rjbs** [comment]
Sorry, I must have missed this issue when it was filed.

There is no built-in retry mechanism.
