### ISSUE TITLE
Single quote in user part results in oddly quoted addr

### ISSUE THREAD

**Issue by lukec** [rjbs/Email-Sender#45]
Hello,

We noticed that an email address with a single quote in the user part, has the user part double quoted, which services like Sendgrid reject as invalid.

Eg: o'neil@foo.com  becomes quoted as "o'neil"@foo.com.  Exim and Postfix appear to handle this okay, but Sendgrid does not - the email address is considered invalid. (I will be checking with Sendgrid to see if they think this behaviour is a bug).

The behaviour happens in `_quoteaddr()` in (at least) SMTP.pm, SMTPS.pm.  If a single quote is added to the `/[^\w.+-]/` regex, then the double quoting of the user part is avoided, and everything is happy.

**Comment by rjbs** [comment]
I have made a trial release, 1.300029, which brings `_quoteaddr` in line with RFC 821… almost.  It does not force quoting on leading on certain forms of dot.  Really, the whole thing isn't quite clear in what it expects, which needs fixing.

This should fix *your* problem, though.  I'm going to let this simmer for a bit before a production release.  LGTY?

**Comment by lukec** [comment]
I think this LGTM!

**Comment by rjbs** [comment]
I've made a stable CPAN release.  Enjoy!
