### ISSUE TITLE
[PATCH] use version->parse for parsing NET::SMTP's version

### ISSUE THREAD

**Issue by real-dam** [rjbs/Email-Sender#46]
In Debian we are currently applying the following patch to
Email-Sender.
We thought you might be interested in it too.

    Description: use version->parse for parsing NET::SMTP's version
     The current version of Net::SMTP in Debian is 3.08_01, which causes a warning
     in Email::Sender::Transport::SMTP:
     .
      Argument "3.08_01" isn't numeric in numeric lt (<) at
      /usr/share/perl5/Email/Sender/Transport/SMTP.pm line 266.

    Bug-Debian: https://bugs.debian.org/847219
    Author: Damyan Ivanov <dmn@debian.org>

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libemail-sender-perl.git/plain/debian/patches/net-smtp-version-cmp.patch

Thanks for considering,
  Damyan Ivanov,
  Debian Perl Group

**Comment by dracos** [comment]
Since https://github.com/rjbs/Email-Sender/commit/0a39b82a1058274c46a45d1033a6629a3ced226e Net::SMTP will always be version 3.07 or above, so this line presumably isn't needed at all any more.

**Comment by mgage** [comment]
I get the same error on a freeBSD installation:

Description: use version->parse for parsing NET::SMTP's version
 The current version of Net::SMTP in Debian is 3.08_01, which causes a warning
 in Email::Sender::Transport::SMTP:

The 3.08_01 version number causes troubles.

**Comment by akarelas-pt** [comment]
I have this problem too. The Perl version I use is v5.24, which comes with this version of Net::SMTP that produces this warning.

**Comment by pali** [comment]
Note that some older version of `version` module are buggy.
See https://metacpan.org/pod/version#SYNOPSIS

And if you need to avoid usage of the `version` module, but still have correct version checking (Net::SMTP is below version 3.07), you can use following code:
```
utf8::downgrade($next_hunk) unless eval { Net::SMTP->VERSION(3.07) };
```

Which would work correctly also if Net::SMTP's version is e.g. 3.08_01.

**Comment by rjbs** [comment]
This should be corrected by #55.

**Comment by ap** [comment]
[Downstream has dropped this patch](https://salsa.debian.org/perl-team/modules/packages/libemail-sender-perl/-/commit/01c3ed7380a0e834bf0389a1e941a1d166c1756d). So this ticket can be closed as well.

> The patch is tracked in our Git repository at
> https://anonscm.debian.org/cgit/pkg-perl/packages/libemail-sender-perl.git/plain/debian/patches/net-smtp-version-cmp.patch

That’s a 404 now so here’s the content of the patch for the record:

<summary>
````diff
--- a/lib/Email/Sender/Transport/SMTP.pm
+++ b/lib/Email/Sender/Transport/SMTP.pm
@@ -11,6 +11,7 @@ use MooX::Types::MooseLike::Base qw(Bool
 use Net::SMTP 3.07; # SSL support, fixed datasend
 
 use utf8 (); # See below. -- rjbs, 2015-05-14
+use version ();
 
 #pod =head1 DESCRIPTION
 #pod
@@ -294,7 +295,8 @@ sub send_email {
     # the mock from ->new.  We don't want to create a new SMTP just to get the
     # version, and we can't rely on $smtp being a Net::SMTP object.
     # -- rjbs, 2015-08-10
-    utf8::downgrade($next_hunk) if (Net::SMTP->VERSION || 0) < 3.07;
+    utf8::downgrade($next_hunk)
+        if version->parse( Net::SMTP->VERSION || 0 ) < 3.07;
 
     $smtp->datasend($next_hunk) or $FAULT->("error at during DATA");
   }
````

**Comment by ap** [comment]
No answer here, but [downstream has dropped this patch in the meantime](https://salsa.debian.org/perl-team/modules/packages/libemail-sender-perl/-/commit/01c3ed7380a0e834bf0389a1e941a1d166c1756d), which I think you can take as a yes. So this ticket can be closed.

**Comment by ap** [comment]
> The patch is tracked in our Git repository at
> https://anonscm.debian.org/cgit/pkg-perl/packages/libemail-sender-perl.git/plain/debian/patches/net-smtp-version-cmp.patch

That’s a 404 now so here’s a copy of the patch for the record:

<details>

````diff
--- a/lib/Email/Sender/Transport/SMTP.pm
+++ b/lib/Email/Sender/Transport/SMTP.pm
@@ -11,6 +11,7 @@ use MooX::Types::MooseLike::Base qw(Bool
 use Net::SMTP 3.07; # SSL support, fixed datasend
 
 use utf8 (); # See below. -- rjbs, 2015-05-14
+use version ();
 
 #pod =head1 DESCRIPTION
 #pod
@@ -294,7 +295,8 @@ sub send_email {
     # the mock from ->new.  We don't want to create a new SMTP just to get the
     # version, and we can't rely on $smtp being a Net::SMTP object.
     # -- rjbs, 2015-08-10
-    utf8::downgrade($next_hunk) if (Net::SMTP->VERSION || 0) < 3.07;
+    utf8::downgrade($next_hunk)
+        if version->parse( Net::SMTP->VERSION || 0 ) < 3.07;
 
     $smtp->datasend($next_hunk) or $FAULT->("error at during DATA");
   }
````

</details>
