### ISSUE TITLE
Email::Sender::Manual::QuickStart erroneously demonstrates using Email::Simple

### ISSUE THREAD

**Issue by jazzkutya** [rjbs/Email-Sender#62]
Email::Sender::Manual::QuickStart shows using Email::Simple but that module is too low on features for a proper quick start. I think It should show using Email::Stuffer because Email::MIME recommends that as an easy to use tool.

**Comment by rjbs** [comment]
Stuffer wouldn't make sense, as it includes sending.  I've just made the example a bit more vague to avoid these details.
